version: '3'
 
services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=dashboard.alaskanresearcher.dev
      - LETSENCRYPT_HOST=dashboard.alaskanresearcher.dev
 
networks:
  default:
    external:
      name: nginx_default
